using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro; // Nos permitir치 trabajar con texto

public class ChuckNorris : MonoBehaviour
{
    public TextMeshProUGUI jokeText;
    public void NewJoke(){
        // Creamos un objeto tipo Joke que se conecte con APIHelper y mande a llamar la funci칩n que nos
        // permite obtener el JSON con la informaci칩n de la p치gina.
        Joke j = APIHelper.GetNewJoke();
        jokeText.text = j.value;
    }
    
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
